import { useState } from 'react';
import { ArrowLeft, ArrowUpRight, Check, Heart, Minus, Plus, ShieldCheck, Truck } from 'lucide-react';
import { Link, useRoute } from 'wouter';
import { formatPrice, getProduct, PRODUCTS, productAccent } from '@/lib/data';
import { PageFrame, useCart } from '@/components/SiteChrome';

export default function Product() {
  const [, params] = useRoute('/shop/:slug');
  const product = getProduct(params?.slug);
  const { add } = useCart();
  const [quantity, setQuantity] = useState(1);
  const [added, setAdded] = useState(false);
  const related = PRODUCTS.filter((item) => item.slug !== product.slug).slice(0, 2);
  const addItem = () => { add(quantity); setAdded(true); window.setTimeout(() => setAdded(false), 2600); };

  return <PageFrame><main className="product-detail"><div className="container"><Link href="/shop" className="back-link"><ArrowLeft size={16} /> Back to all figures</Link><div className="product-detail__grid"><div className="product-detail__visual" style={productAccent(product)}><span className="product-detail__edition">Edition {product.number} / 06</span><img src={product.image} alt={product.name} /><div className="product-detail__circle">TOONHUB BY AADI<br />HAND FINISHED<br />2026</div></div><div className="product-detail__info"><p className="eyebrow">{product.collection} / Figure {product.number}</p><h1>{product.name}</h1><p className="product-detail__price">{formatPrice(product.price)}</p><p className="product-detail__blurb">{product.blurb}</p><div className="product-detail__rule" /><div className="product-accordions"><details open><summary>Details <Plus size={16} /></summary><div className="detail-list">{product.details.map((detail) => <span key={detail}><Check size={15} />{detail}</span>)}</div></details><details><summary>Shipping & returns <Plus size={16} /></summary><p>Ships in 2–4 business days, wrapped in recycled paper and packed for a safe landing. Returns accepted within 30 days.</p></details></div><div className="purchase-row"><div className="quantity"><button onClick={() => setQuantity((value) => Math.max(1, value - 1))} aria-label="Decrease quantity"><Minus size={15} /></button><span>{quantity.toString().padStart(2, '0')}</span><button onClick={() => setQuantity((value) => value + 1)} aria-label="Increase quantity"><Plus size={15} /></button></div><button className={`button button--dark purchase-button ${added ? 'is-added' : ''}`} onClick={addItem}>{added ? <><Check size={17} /> Added to bag</> : <>Add to bag <ArrowUpRight size={17} /></>}</button><button className="wishlist-button" aria-label="Add to wishlist"><Heart size={18} /></button></div><div className="product-trust"><span><Truck size={16} /> Free shipping over $120</span><span><ShieldCheck size={16} /> Secure checkout</span></div></div></div><div className="product-story"><div><p className="eyebrow">A closer look</p><h2>Small details.<br /><em>Big personality.</em></h2></div><p>Designed to sit quietly in the corner of your eye and make you smile when you least expect it. Put this one somewhere with good light.</p></div><div className="related-row"><div className="section-heading"><div><p className="eyebrow">You may also like</p><h2>More good company</h2></div><Link href="/shop" className="text-link">View all <ArrowUpRight size={16} /></Link></div><div className="product-grid product-grid--two">{related.map((item) => <div key={item.slug} className="related-card"><img src={item.image} alt={item.name} /><div><p className="eyebrow">{item.collection}</p><h3>{item.name}</h3><Link href={`/shop/${item.slug}`} className="text-link">View figure <ArrowUpRight size={15} /></Link></div></div>)}</div></div></div></main></PageFrame>;
}
